package com.example.courslens.api;
import com.example.courslens.api.Dtos.*; import com.example.courslens.domain.*; import com.example.courslens.repository.*; import com.example.courslens.service.*; import org.apache.pdfbox.Loader; import org.apache.pdfbox.pdmodel.PDDocument; import org.springframework.core.io.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.io.*; import java.nio.file.*; import java.util.*;
@RestController @RequestMapping("/api") @CrossOrigin public class CourseController {
 private final IngestionService ingestion;private final DocumentRepository docs;private final PageRepository pages;private final ChunkRepository chunks;private final QuestionService questions; private final ChatMessageRepository messages;
 CourseController(IngestionService i,DocumentRepository d,PageRepository p,ChunkRepository c,QuestionService q,ChatMessageRepository m){ingestion=i;docs=d;pages=p;chunks=c;questions=q;messages=m;}
 @GetMapping("/documents") List<DocumentView> list(){return docs.findAll().stream().map(this::view).toList();}
 @GetMapping("/documents/{id}") DocumentView one(@PathVariable UUID id){return view(docs.findById(id).orElseThrow());}
 @GetMapping("/documents/{id}/pages") List<PageView> pages(@PathVariable UUID id){if(!docs.existsById(id))throw new NoSuchElementException();return pages.findByDocumentIdOrderByPageNumber(id).stream().map(p->new PageView(p.id,p.pageNumber,p.extractedText,p.handwritten)).toList();}
 @GetMapping("/documents/{id}/chunks") List<ChunkView> chunks(@PathVariable UUID id){if(!docs.existsById(id))throw new NoSuchElementException();return chunks.findByDocumentIdWithPage(id).stream().map(c->new ChunkView(c.id,c.page.id,c.page.pageNumber,c.chunkIndex,c.text,c.embedding==null?0:c.embedding.length)).toList();}
 @PostMapping(value="/documents",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) ResponseEntity<DocumentView> upload(@RequestParam("file")MultipartFile file){Document document=ingestion.ingest(file);return ResponseEntity.status("FAILED".equals(document.status)?HttpStatus.UNPROCESSABLE_ENTITY:HttpStatus.CREATED).body(view(document));}
 @PostMapping("/questions") AskResponse ask(@RequestBody AskRequest request){return questions.ask(request);}
 @GetMapping("/conversations/{id}/messages") List<MessageView> conversation(@PathVariable UUID id){return messages.findBySessionIdOrderByCreatedAt(id).stream().map(m->new MessageView(m.id,m.role.name(),m.content,m.createdAt)).toList();}
 @GetMapping("/documents/{id}/pages/{number}/source") ResponseEntity<Resource> source(@PathVariable UUID id,@PathVariable int number)throws Exception {Page page=pages.findWithDocumentByDocumentIdAndPageNumber(id,number).orElseThrow(); if("PDF".equals(page.document.type)){return isolatedPdfPage(page);} if("IMAGE".equals(page.document.type)&&page.imagePath!=null){Path image=Path.of(page.imagePath);String mime=Optional.ofNullable(Files.probeContentType(image)).orElse(MediaType.APPLICATION_OCTET_STREAM_VALUE);return file(page,image,MediaType.parseMediaType(mime));} byte[] text=Optional.ofNullable(page.extractedText).orElse("").getBytes(java.nio.charset.StandardCharsets.UTF_8);return ResponseEntity.ok().header("X-CourseLens-Source-Number",Integer.toString(number)).contentType(MediaType.TEXT_PLAIN).body(new ByteArrayResource(text));}
 private ResponseEntity<Resource> isolatedPdfPage(Page page)throws IOException {try(PDDocument original=Loader.loadPDF(Path.of(page.document.storagePath).toFile());PDDocument one=new PDDocument();ByteArrayOutputStream out=new ByteArrayOutputStream()){one.importPage(original.getPage(page.pageNumber-1));one.save(out);one.close();return ResponseEntity.ok().header("Content-Disposition","inline; filename=page-"+page.pageNumber+".pdf").header("X-CourseLens-Source-Number",Integer.toString(page.pageNumber)).contentType(MediaType.APPLICATION_PDF).body(new ByteArrayResource(out.toByteArray()));}}
 private ResponseEntity<Resource> file(Page page,Path path,MediaType type){return ResponseEntity.ok().header("X-CourseLens-Source-Number",Integer.toString(page.pageNumber)).contentType(type).body(new FileSystemResource(path));}
 @ExceptionHandler({IllegalArgumentException.class}) ResponseEntity<Map<String,String>> badRequest(IllegalArgumentException ex){return ResponseEntity.badRequest().body(Map.of("error",ex.getMessage()));}
 private DocumentView view(Document d){return new DocumentView(d.id,d.filename,d.type,d.status,d.pageCount,d.createdAt,d.processingError);}
}
